name: Deploy Angular Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'demo-ui/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & build Angular
        working-directory: demo-ui
        run: |
          npm install
          npm run build --prod

      - name: Build Docker image
        run: docker build -t demo-ui ./demo-ui

      - name: Build Docker image
        working-directory: demo
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-ui:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-ui:latest