name: Build & Deploy Backend to DockerHub

on:
  push:
    branches: [ main ]
    paths:
      - 'demo/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot project
        working-directory: demo
        run: mvn clean package -DskipTests

      - name: Build Docker image
        working-directory: demo
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-backend:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-backend:latest

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
